# Generated by Django 3.2.8 on 2021-10-22 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_my_userdetails'),
    ]

    operations = [
        migrations.DeleteModel(
            name='My_UserDetails',
        ),
    ]
