# Generated by Django 3.2.8 on 2021-11-27 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_delete_my_userdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='currentBidAmount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='bid',
            name='currentBidAmount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='product',
            name='Nature',
            field=models.CharField(choices=[('sh', 'shareable'), ('unsh', 'unshareable')], default='unsh', max_length=200),
        ),
    ]
