# Generated by Django 3.2.8 on 2021-12-13 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_auto_20211213_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='number_of_bids',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
