# Generated by Django 3.2.8 on 2021-12-13 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_auction_number_of_bids'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='score',
            field=models.FloatField(default=0.0),
        ),
    ]
