# Generated by Django 3.2.8 on 2021-12-14 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_bid_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='base_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='bid',
            name='qte',
            field=models.FloatField(default=0.0),
        ),
    ]
